### ISSUE TITLE
Cannot import module with "crypto" and "dgram" dependancy errors.

### ISSUE THREAD

**Issue by AdrianV2552** [coapjs/node-coap#359]
I am receiving the error shown below with the modules "crypto" and "dgram". I looked on the npm website and crypto says it is not being supported anymore, and dgram is being held for security reasons. I am trying to use this module on react native with the expo emulator. It is not working due to this import error.
![IMG_0507](https://user-images.githubusercontent.com/112202947/205520774-4ab7c3d1-43dc-4c1f-9a9e-6084b2d7cc57.jpg)

**Comment by JKRhb** [comment]
Hi @AdrianV2552, thanks for opening this issue! It seems the problem lies in the fact that Node.js libraries such as crypto and dgram are not available in React Native and require workarounds or the import of specific replacements (such as [react-native-crypto](https://www.npmjs.com/package/react-native-crypto) or [react-native-udp](https://www.npmjs.com/package/react-native-udp)). Maybe you could try forking node-coap and adding these two dependencies?

**Comment by AdrianV2552** [comment]
I tried replacing both, but they are used in a lot of files, and it just kept leading to even more module errors. Im thinking about going back to an older react native version but im not sure that will work. other wise i'll be doing a lot of replacing.

**Comment by AdrianV2552** [comment]
yeah I have had replaced both, and now I have just gone through a loop of errors. I am now on "super expression must either be null or a function" for the coap module in either index.js or observewritestream.js.

**Comment by JKRhb** [comment]
Hi @AdrianV2552, just wanted to ask if you found a solution in the meantime? :/

**Comment by JKRhb** [comment]
I'll close this issue for the time being, let me know if you think we could still make some progress here somehow, then we could reopen it.
